version: '3.8'

services:
  # 1. Servicio de la API de Backend
  backend-api:
    build: .                      # Construir imagen desde Dockerfile
    container_name: backend_api_service
    # No exponer puertos directamente; Nginx se encargará

  # 2. Servicio del Servidor Web (Proxy Inverso con Nginx)
  web-server:
    image: nginx:latest
    container_name: nginx_proxy_service
    ports:
      - "80:80"                   # Exponer puerto 80 del contenedor al host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Montar configuración personalizada
    depends_on:
      - backend-api               # Asegurar que el backend esté disponible
